### ISSUE TITLE
Thoughts on future of PWA?

### ISSUE THREAD

**Issue by rajatpundir** [jakearchibald/jakearchibald.com#37]

**Comment by jakearchibald** [comment]
huh, I was planning to read and reply to this 😄

**Comment by rajatpundir** [comment]
> huh, I was planning to read and reply to this

await reply()

**Comment by jakearchibald** [comment]
The balance between client vs server is tough to figure out. It tends to be about weighing up-front cost vs runtime cost. The script seems a little large to me (600kB gzipped), which seems to contribute to most of the long loading time. I'm not sure what's in that bundle, is it all necessary? It does run nicely once it's downloaded though.

> I wanted to know your thoughts on how future will unfold for PWAs

Ohh, that's a big question! I'm not sure. I think the biggest thing holding us back right now is Safari on iOS. The wealthiest people tend to have iPhones, and those people are restricted to a browser developed by a company that doesn't seem to believe in apps in the browser, and wants to keep the web for documents only.

**Comment by rajatpundir** [comment]
> The balance between client vs server is tough to figure out. It tends to be about weighing up-front cost vs runtime cost. The script seems a little large to me (600kB gzipped), which seems to contribute to most of the long loading time. I'm not sure what's in that bundle, is it all necessary? It does run nicely once it's downloaded though.
> 

I have not yet focused reducing its, I have thoughts that most code could be compressed in a final version by writing some generic code, but I don't know how that generic code would look like in future so I have delayed that part. Some 200kb could be reduced by removing unused tailwindcss classes. I plan to address the issue when I have a better view what features final application would end up with. Some slow initial loading is also due to app being hosted on a free heroku instance which goes to sleep if it doesn't see much activity and takes a while to start again.

> > I wanted to know your thoughts on how future will unfold for PWAs
> 
> Ohh, that's a big question! I'm not sure. I think the biggest thing holding us back right now is Safari on iOS. The wealthiest people tend to have iPhones, and those people are restricted to a browser developed by a company that doesn't seem to believe in apps in the browser, and wants to keep the web for documents only.

I dont have much knowledge to say on the matter but I think breaking walled gardens is neither easy nor efficient. Having an app for iPhones would surely create advantages for a company which may also decrease their interests in creating and maintaing PWAs. PWAs main selling point should be not having to install the app to start using it. 

I have an idea that I plan on trying out sometime later this year or next. The idea is as following:
  What most businesses want is an app for their specific domain but they cannot afford the development/maintenance cost or the quality of the app is most likely going to be mediocre. So what these businesses prefer is to rather domain speciliased platforms where they don't have to worry about this.
  But these business still want their own apps because of following reasons: 1. Don't want to pay platform fees, 2. There is competetion on platform, 3. If they had their own app, they could market it and have a rally point around which they could make a loyal customer base. Platforms are brutal where customer reviews are keeping these vendors in check, but even if they had their own apps, they would still be competing with others to grow their base of loyal customers.
  What a smarter platform could do is to let these vendors have their own subdomains and PWAs where other businesses are not listed so that they could use that PWA link for marketing purposes. So from our perspective, we have a market force here that can push adoption of PWAs from the seller side if not from the buyer side.
