### ISSUE TITLE
Caching static assets

### ISSUE THREAD

**Issue by kevinfarrugia** [jakearchibald/jakearchibald.com#43]
How come you choose to revalidate your static assets even if you are using a hash in the URL?

**/c/analytics-4406ed07.js**
```
cache-control: public, max-age=0, must-revalidate
```

(not sure if this is the right place to ask questions 😁)

**Comment by jakearchibald** [comment]
That's a good question. I must have messed up some config. I'm pretty sure these used to cache.

**Comment by jakearchibald** [comment]
Fixed in https://github.com/jakearchibald/jakearchibald.com/commit/6673519b86a62baa1fdafabff29677c457c66d6b. Thanks for catching this! I wrote some really dumb code along with my CORS article and broke caching.
